---
namespace: trippsc2
name: duo
version: 1.0.15
readme: README.md
authors:
  - Jim Tarpley (@trippsc2)
description: This collection contains modules and roles for configuring Cisco DUO.

license_file: 'LICENSE'

tags:
  - application
  - infrastructure
  - linux
  - security

dependencies:
  ansible.posix: ">=1.0.1"
  ansible.utils: ">=2.5.0"
  community.general: ">=8.1.0"

repository: https://github.com/trippsoft/ansible-collection-duo.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
