---
- name: Validate
  ansible.builtin.import_tasks: validate/main.yml

- name: Install dependencies
  ansible.builtin.import_tasks: prepare.yml

- name: Install Duo Authentication Proxy
  ansible.builtin.import_tasks: install/main.yml

- name: Configure Duo Authentication Proxy
  ansible.builtin.import_tasks: configure.yml

- name: Configure firewalld
  when:
    - duoap_configure_firewall
    - _duoap_firewall_type == 'firewalld'
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure ufw
  when:
    - duoap_configure_firewall
    - _duoap_firewall_type == 'ufw'
  ansible.builtin.include_tasks: ufw.yml
