---
_duoap_configure_selinux: >-
  {{ duoap_configure_selinux | default(_duoap_default_configure_selinux) }}
_duoap_firewall_type: >-
  {{ duoap_firewall_type | default(_duoap_default_firewall_type) }}
_duoap_http_ca_certs_file: >-
  {{ duoap_http_ca_certs_file | default(_duoap_default_http_ca_certs_file) }}

_duoap_radius_enabled: "{{ duoap_radius_auto_servers | length > 0 }}"

_duoap_log_max_size: "{{ duoap_log_max_size_in_mb | int * 1024 * 1024 }}"
