---
galaxy_info:
  author: Jim Tarpley (@trippsc2)
  namespace: trippsc2
  role_name: duo_authentication_proxy
  description: This role installs and configures a DUO Authentication Proxy on a Linux machine.

  license: MIT

  min_ansible_version: '2.16'

  platforms:
    - name: Debian
      versions:
        - bookworm
    - name: EL
      versions:
        - '9'
        - '8'
    - name: Ubuntu
      versions:
        - noble
        - jammy
        - focal

collections:
  - ansible.posix
  - ansible.utils
  - community.general

dependencies: []
