---
name: Generate Role Docs - authentication_proxy role
'on':
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs-authentication_proxy.yml
      - roles/authentication_proxy/.aar_doc.yml
      - roles/authentication_proxy/meta/argument_specs.yml
      - roles/authentication_proxy/meta/main.yml
defaults:
  run:
    working-directory: 'trippsc2.duo'
jobs:
  docs:
    name: Generate authentication_proxy role documentation
    permissions:
      contents: write
    uses: trippsoft/github-actions/.github/workflows/role-docs.yml@main
    with:
      working_directory: 'trippsc2.duo'
      role_name: 'authentication_proxy'
